
export const gameCategories = [
  { value: 'anime', label: 'Anime' },
  { value: 'cyberpunk', label: 'Cyberpunk' },
  { value: 'detective', label: 'Detektivní' },
  { value: 'based', label: 'Dle předlohy' },
  { value: 'fantasy', label: 'Fantasy' },
  { value: 'furry', label: 'Furry' },
  { value: 'history', label: 'Historické' },
  { value: 'horror', label: 'Horor' },
  { value: 'comedy', label: 'Komedie' },
  { value: 'scifi', label: 'Sci-fi' },
  { value: 'steampunk', label: 'Steampunk' },
  { value: 'strategy', label: 'Strategie' },
  { value: 'survival', label: 'Survival' },
  { value: 'urban', label: 'Urban Fantasy' },
  { value: 'relationship', label: 'Vztahové' },
  { value: 'other', label: 'Ostatní' }
]

export const gameSystems = [
  { value: 'base', label: 'Jiný / Bez systému' },
  { value: 'dnd5', label: 'Dungeons & Dragons e5' },
  { value: 'vampire5', label: 'Vampire the Masquerade e5' },
  { value: 'yearzero', label: 'Year Zero Engine' },
  { value: 'drd1', label: 'Dračí doupě e1.6' },
  { value: 'cyberpunk', label: 'Cyberpunk 2020' },
  { value: 'starwars', label: 'Star Wars' },
  { value: 'cthulhu', label: 'Call of Cthulhu' },
  { value: 'warhammer', label: 'Warhammer' },
  { value: 'shadowrun', label: 'Shadowrun' },
  { value: 'pathfinder', label: 'Pathfinder' },
  { value: 'mutant', label: 'Mutant' },
  { value: 'gurps', label: 'GURPS' },
  { value: 'fate', label: 'Fate' },
  { value: 'savage', label: 'Savage Worlds' },
  { value: 'dungeonworld', label: 'Dungeon World' },
  { value: 'other', label: 'Ostatní' }
]

export const workCategoriesText = [
  { value: 'prose', label: 'Próza' },
  { value: 'poetry', label: 'Poezie' },
  { value: 'game', label: 'Herní' },
  { value: 'other', label: 'Ostatní' }
]

export const workTags = [
  { value: 'story', label: 'Povídka' },
  { value: 'fantasy', label: 'Fantasy' },
  { value: 'steampunk', label: 'Steampunk' },
  { value: 'scifi', label: 'Sci-fi' },
  { value: 'horror', label: 'Horor' },
  { value: 'detective', label: 'Detektivka' },
  { value: 'thriller', label: 'Thriller' },
  { value: 'romance', label: 'Romantika' },
  { value: 'dystopia', label: 'Dystopie' },
  { value: 'poem', label: 'Báseň' },
  { value: 'epos', label: 'Epos' },
  { value: 'drama', label: 'Drama' },
  { value: 'haiku', label: 'Haiku' },
  { value: 'sonnet', label: 'Sonet' },
  { value: 'freeverse', label: 'Volný verš' },
  { value: 'tragedy', label: 'Tragédie' },
  { value: 'comedy', label: 'Komedie' },
  { value: 'tragicomedy', label: 'Tragikomedie' },
  { value: 'monodrama', label: 'Monodrama' },
  { value: 'experimental', label: 'Experimentální' },
  { value: 'screenplay', label: 'Scénář' },
  { value: 'fromlife', label: 'Ze života' },
  { value: 'biography', label: 'Biografie' },
  { value: 'essay', label: 'Esej' },
  { value: 'history', label: 'Historie' },
  { value: 'motivational', label: 'Motivační' },
  { value: 'fairytale', label: 'Pohádka' },
  { value: 'educational', label: 'Vzdělávací' },
  { value: 'comics', label: 'Komiks' },
  { value: 'superhero', label: 'Superhrdinské' },
  { value: 'manga', label: 'Manga' },
  { value: 'travel', label: 'Cestopis' },
  { value: 'religion', label: 'Nábožeství' },
  { value: 'science', label: 'Věda' },
  { value: 'technology', label: 'Technologie' },
  { value: 'futurism', label: 'Futurismus' },
  { value: 'philosophy', label: 'Filosofie' },
  { value: 'rpg', label: 'RPG' },
  { value: 'larp', label: 'LARP' },
  { value: 'fanfiction', label: 'Fanfikce' },
  { value: 'erotica', label: 'Erotika' },
  { value: 'parody', label: 'Parodie' },
  { value: 'city', label: 'Město' },
  { value: 'countryside', label: 'Venkov' },
  { value: 'space', label: 'Vesmír' },
  { value: 'vampires', label: 'Upíři' },
  { value: 'werewolves', label: 'Vlkodlaci' },
  { value: 'zombies', label: 'Zombie' },
  { value: 'magic', label: 'Magie' },
  { value: 'warhammer', label: 'Warhammer' },
  { value: 'dnd', label: 'D&D' },
  { value: 'drd', label: 'DrD' },
  { value: 'cyberpunk', label: 'Cyberpunk' },
  { value: 'shadowrun', label: 'Shadowrun' },
  { value: 'cthulhu', label: 'Cthulhu' },
  { value: 'lotr', label: 'Pán prstenů' },
  { value: 'harrypotter', label: 'Harry Potter' },
  { value: 'starwars', label: 'Star Wars' },
  { value: 'startrek', label: 'Star Trek' },
  { value: 'andor', label: 'Andor' },
  { value: 'project', label: 'Projektíček' }
]
