begin;

create table public.wall (
  id int4 not null primary key generated by default as identity,
  post int4[] not null,
  title text not null default '',
  content_type text not null default 'text',
  content_id int4,
  image_url text,
  subheadline text,
  button_text text,
  url text,
  published boolean default false,
  owner uuid default auth.uid(),
  character_name text,
  created_at timestamptz default current_timestamp,
  constraint wall_post_not_empty check (cardinality(post) > 0),
  constraint wall_owner_fkey foreign key (owner) references public.profiles(id) on delete cascade
);

create index idx_wall_post on public.wall using gin (post);
create index idx_wall_published_created_at on public.wall (published, created_at desc);
create index idx_wall_owner on public.wall (owner);

create or replace function public.is_admin () returns boolean as $$
  select coalesce(auth.uid() = any(array[
    '2d7898ea-ac7b-4f1b-bf29-a10c28892835'::uuid,
    '6d3c87ea-aacc-4fd6-9859-852894fd3092'::uuid
  ]), false);
$$ language sql stable security definer set search_path = public;

alter table public.posts disable trigger user;

create table public.news_reactions_backup as
select * from public.reactions where item_type = 'news';
alter table public.news_reactions_backup add primary key (item_id);
delete from public.reactions where item_type = 'news';

do $$
declare
  news_row record;
  new_post_id int4;
  old_reaction record;
begin
  for news_row in select * from public.news order by id loop
    insert into public.posts (owner, owner_type, content, created_at, updated_at)
    values (
      coalesce(news_row.character, news_row.owner),
      case when news_row.character is null then 'user' else 'character' end,
      news_row.content,
      news_row.created_at,
      news_row.created_at
    )
    returning id into new_post_id;

    insert into public.wall (
      post,
      title,
      content_type,
      content_id,
      image_url,
      subheadline,
      button_text,
      url,
      published,
      owner,
      character_name,
      created_at
    ) values (
      array[new_post_id],
      news_row.title,
      news_row.content_type,
      news_row.content_id,
      news_row.image_url,
      news_row.subheadline,
      news_row.button_text,
      news_row.url,
      news_row.published,
      news_row.owner,
      news_row.character_name,
      news_row.created_at
    );

    select * into old_reaction
    from public.news_reactions_backup
    where item_id = news_row.id and item_type = 'news';

    if found then
      insert into public.reactions (item_id, item_type, thumbs, frowns, shocks, hearts, laughs)
      values (new_post_id, 'post', old_reaction.thumbs, old_reaction.frowns, old_reaction.shocks, old_reaction.hearts, old_reaction.laughs);
    end if;
  end loop;
end;
$$;

alter table public.posts enable trigger user;

drop view if exists public.news_reactions;
alter table public.reactions drop constraint if exists reactions_item_type_check;
alter table public.reactions add constraint reactions_item_type_check check (item_type = 'post');
alter table public.news rename to news_backup;
alter table public.news_backup rename constraint news_pkey to news_backup_pkey;
alter table public.news_backup drop constraint news_owner_fkey;
comment on table public.news_backup is 'Read-only backup of news before migration to posts and wall on 2026-08-10.';

alter table public.news_backup enable row level security;
drop policy if exists "READ for everyone" on public.news_backup;
create policy "READ news backup for admins" on public.news_backup
for select to authenticated using (public.is_admin());
revoke all on public.news_backup from anon, authenticated;
grant select on public.news_backup to authenticated;

alter table public.news_reactions_backup enable row level security;
create policy "READ news reactions backup for admins" on public.news_reactions_backup
for select to authenticated using (public.is_admin());
revoke all on public.news_reactions_backup from anon, authenticated;
grant select on public.news_reactions_backup to authenticated;

create or replace view public.wall_posts with (security_invoker = true) as
  select
    w.id as wall_id,
    root.id,
    w.post,
    w.title,
    w.content_type,
    w.content_id,
    w.image_url,
    w.subheadline,
    w.button_text,
    w.url,
    root.content,
    w.published,
    w.owner,
    author.id as owner_id,
    author.name as owner_name,
    author.portrait as owner_portrait,
    case when root.owner_type = 'character' then root.owner end as character,
    case when root.owner_type = 'character' then coalesce(character_owner.name, w.character_name) end as character_name,
    w.created_at,
    root.updated_at,
    reaction.thumbs,
    reaction.frowns,
    reaction.shocks,
    reaction.hearts,
    reaction.laughs
  from public.wall w
  join public.posts root on root.id = w.post[1]
  left join public.profiles author on w.owner = author.id
  left join public.characters character_owner on root.owner = character_owner.id and root.owner_type = 'character'
  left join public.reactions reaction on root.id = reaction.item_id and reaction.item_type = 'post';

create or replace function public.validate_wall_posts () returns trigger as $$
begin
  if cardinality(new.post) = 0 or (
    select count(*) from public.posts where id = any(new.post)
  ) <> cardinality(new.post) then
    raise exception 'Wall musí obsahovat neprázdné pole existujících příspěvků';
  end if;
  return new;
end;
$$ language plpgsql set search_path = public;

create or replace function public.remove_post_from_wall () returns trigger as $$
begin
  delete from public.wall where old.id = any(post) and cardinality(post) = 1;
  update public.wall set post = array_remove(post, old.id) where old.id = any(post);
  return old;
end;
$$ language plpgsql set search_path = public;

create or replace function public.create_wall_entry (new_content text, is_published boolean default true) returns int4 as $$
declare
  new_post_id int4;
  new_wall_id int4;
begin
  if not public.is_admin() then raise exception 'Příspěvky na zeď může přidávat jen administrátor'; end if;
  if length(trim(new_content)) = 0 then raise exception 'Příspěvek nesmí být prázdný'; end if;

  insert into public.posts (owner, owner_type, content)
  values (auth.uid(), 'user', new_content)
  returning id into new_post_id;

  insert into public.wall (post, published, owner)
  values (array[new_post_id], is_published, auth.uid())
  returning id into new_wall_id;

  return new_wall_id;
end;
$$ language plpgsql security definer set search_path = public;

create or replace function public.update_wall_entry (wall_id int4, new_content text) returns void as $$
declare
  root_post_id int4;
begin
  if not public.is_admin() then raise exception 'Příspěvky na zdi může upravovat jen administrátor'; end if;
  if length(trim(new_content)) = 0 then raise exception 'Příspěvek nesmí být prázdný'; end if;

  select post[1] into root_post_id from public.wall where id = wall_id;
  if root_post_id is null then raise exception 'Příspěvek na zdi neexistuje'; end if;
  update public.posts set content = new_content where id = root_post_id;
end;
$$ language plpgsql security definer set search_path = public;

create or replace function public.delete_wall_entry (wall_id int4) returns void as $$
declare
  post_ids int4[];
begin
  if not public.is_admin() then raise exception 'Příspěvky ze zdi může mazat jen administrátor'; end if;

  delete from public.wall where id = wall_id returning post into post_ids;
  if post_ids is null then raise exception 'Příspěvek na zdi neexistuje'; end if;
  delete from public.posts where id = any(post_ids);
end;
$$ language plpgsql security definer set search_path = public;

create trigger validate_wall_posts_before_write
before insert or update of post on public.wall
for each row execute function public.validate_wall_posts();

create trigger remove_post_from_wall_after_delete
after delete on public.posts
for each row execute function public.remove_post_from_wall();

alter table public.wall enable row level security;

create policy "READ published wall entries" on public.wall
for select to public using (published = true or public.is_admin());
create policy "INSERT wall entries for admins" on public.wall
for insert to authenticated with check (public.is_admin());
create policy "UPDATE wall entries for admins" on public.wall
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "DELETE wall entries for admins" on public.wall
for delete to authenticated using (public.is_admin());

do $$
declare
  existing_qual text;
begin
  select pg_get_expr(policy.polqual, policy.polrelid)
  into existing_qual
  from pg_policy policy
  where policy.polrelid = 'public.posts'::regclass
    and policy.polname = 'posts_select_policy';

  if existing_qual is null then raise exception 'Policy posts_select_policy neexistuje'; end if;
  execute format(
    'alter policy posts_select_policy on public.posts using ((%s) or exists (select 1 from public.wall where posts.id = any(wall.post) and (wall.published = true or public.is_admin())))',
    existing_qual
  );
end;
$$;

grant select on public.wall_posts to anon, authenticated;
grant select on public.wall to anon, authenticated;
revoke execute on function public.create_wall_entry(text, boolean) from public, anon;
revoke execute on function public.update_wall_entry(int4, text) from public, anon;
revoke execute on function public.delete_wall_entry(int4) from public, anon;
grant execute on function public.create_wall_entry(text, boolean) to authenticated;
grant execute on function public.update_wall_entry(int4, text) to authenticated;
grant execute on function public.delete_wall_entry(int4) to authenticated;

commit;
